services:
  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      API_PREFIX: ${API_PREFIX}
      I18N_DEFAULT_LANG: ${I18N_DEFAULT_LANG}
      I18N_FALLBACK_LANG: ${I18N_FALLBACK_LANG}
    ports:
      - "3000:3000"
